server.port=8080

spring.datasource.url=jdbc:mysql://${DB_HOST:mysql.app.svc.cluster.local}:${DB_PORT:3306}/${DB_NAME:appdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASSWORD:AppP@ss123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
